# Initalize
init:
  - git config --global core.autocrlf true

image: Visual Studio 2019

build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 --target "appveyor"

test: on

branches:
  only:
    - master
    - develop

skip_tags: true
